sudo: false
language: python
services:
  - redis
python:
  - "3.6"
install:
  - pip install -e .
  - pip install --upgrade pytest pytest-cov coveralls pytest-mock flake8 flake8-isort
script:
  - pytest --cov redis_tasks --run-slow
  - flake8 .
after_success:
  - coveralls
