language: python
os: linux
dist: "focal"
services:
  - redis
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
install:
  - pip install tox-travis 'tox<4'  # incompatible with tox>=4
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
