language: python
os: linux
dist: "bionic"
services:
  - redis
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest-cov coveralls flake8 flake8-isort
script:
  - pytest --cov redis_tasks --run-slow
  - flake8 .
after_success:
  - coveralls
