language: python
os: linux
dist: "bionic"
services:
  - redis
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
