DEFAULT_TASK_TIMEOUT = 60 * 60 * 24  # 1 day
EXPIRING_REGISTRIES_TTL = 60 * 60 * 24 * 7  # 7 days
DEAD_WORKER_TTL = 60 * 60  # 1 hour
WORKER_HEARTBEAT_FREQ = 10  # 10 seconds
WORKER_HEARTBEAT_TIMEOUT = 60  # 1 minute
MAINTENANCE_FREQ = 60 * 1  # 1 minute

REDIS_URL = "redis://127.0.0.1:6379"
REDIS_PREFIX = "rq"
TASK_MIDDLEWARES = []
WORKER_PRELOAD_FUNCTION = None
WORKER_DESCRIPTION_FUNCTION = "rq.worker_process.generate_worker_description"
