version: 1

update_configs:
  # python updates
  - package_manager: "python"
    directory: "/"
    version_requirement_updates: "auto"
    default_reviewers:
      - "i-trofimtschuk"
      - "vasilty"
      - "kaloyanm"
      - "djangsters/backend"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_type: "direct"
